---
resource_types:
  - name: "aws-cloudformation-stack"
    type: "docker-image"
    source:
      repository: "dpb587/aws-cloudformation-stack-resource"
      tag: "master"


resources:
  - name: "repo"
    type: "git"
    source:
      uri: {{repo_uri}}
      branch: {{repo_branch}}
      private_key: {{private-repo-key}}
      username: {{repo-username}}
  - name: "bastion-stack"
    type: "aws-cloudformation-stack"
    source:
      name: "repo"
      access_key: {{aws_access_key}}
      secret_key: {{aws_secret_key}}
      region: {{aws_region}}


jobs:
  - name: "test-deploy"
    serial: true
    plan:
      - aggregate:
          - get: "repo"
            trigger: true
      - put: "bastion-stack"
        params:
          template: "repo/cfn_template.json"
          parameters: "repo/parameters.json"


